### PR TITLE
Add missing migration

### PR DESCRIPTION
**Pull request by markus-hinsche**
A migration file was missing. 
When we used the tinycontent app in our project, `manage.py makemigrations` would always tell us that it created the migration file.

### CODE REVIEW

**Comment by markus-hinsche** [comment]
@dominicrodger Any thoughts on this?

**Comment by dominicrodger** [comment]
Apologies @markus-hinsche - it's been a busy few days for me. Taking a look now.

**Comment by dominicrodger** [comment]
I'm confused by this - makemigrations doesn't make anything for me, and the model being changed in the migration hasn't changed in two years. What version of Python are you using? Are you using a virtualenv? If so, could you post the output of `pip freeze`?

**Comment by markus-hinsche** [comment]
Using python 3, see `pip freeze` output here: 
https://gist.github.com/markus-hinsche/936a7bdcf80c8c76d7dfbbaf538bc919

**Comment by markus-hinsche** [comment]
It seems that migration `0002_tinycontentfileupload` and `0003_update_slug` was introducing the some parameters of the fields `name`, `slug` and `file` as bytes type:

```
                ('name', models.CharField(help_text=b'The name of the file.', max_length=60)),
                ('file', models.FileField(upload_to=b'tinycontent/uploads')),
```

`            field=autoslug.fields.AutoSlugField(populate_from=b'name', unique=True, editable=False),`

**Comment by markus-hinsche** [comment]
@dominicrodger Thoughts?

**Comment by dominicrodger** [comment]
Sorry @markus-hinsche, been struggling to find time for open source work. I believe you're correct - just want to make sure that adding the extra migration won't cause problems for Python 2 users.

**Comment by markus-hinsche** [comment]
Sure, let me know if I can help

**Comment by dominicrodger** [comment]
I've fixed this in 2ecfce0bcc2849b97eedb8b21f33bfc8ff7b1659 (I didn't merge this pull request, since I wanted to rename the migration, hope that's OK). I'll push v0.7.1 to PyPI later today. I'll update and close the ticket when that's done.

Thanks for your help @markus-hinsche, much appreciated.

**Comment by dominicrodger** [comment]
I've released 0.7.1 with this fix - thanks again for your help! Feel free to open an issue if you run into any problems with it.

**Pull request closed without merging**
